### ISSUE TITLE
Enhance controlplane webhooks to add provider-specific settings to /etc/sysctl.d/99-k8s-general.conf

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener-extensions#113]
For some providers (namely AWS and GCP), Gardener adds provider-specific settings to the file `/etc/sysctl.d/99-k8s-general.conf` which is part of the `OperatingSystemConfig` resource, see https://github.com/gardener/gardener/blob/eb083ff1f87b131f2c27ddb488e4ca16d24a9b39/charts/seed-operatingsystemconfig/original/templates/config/_99-k8s-general.conf#L57-L64.
The corresponding controlplane webhooks for AWS and GCP should add these settings as well.

**Comment by rfranzke** [comment]
@svetlinas is taking over this one.
