### ISSUE TITLE
Minimal Permissions for Azure/GCP/OpenStack Shoot Clusters

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener-extensions#133]
We have narrowed down the access permissions for AWS shoot clusters (potential remainder tracked in #178), but not yet for Azure, GCP and OpenStack, which this ticket is now about. We expect less success on these infrastructures as AWSes permision/policy options are very detailed. This may break the "shared account" idea on these infrastructures (Azure and GCP - OpenStack can be mitigated by programmatically creating tenants on the fly).

**Comment by rfranzke** [comment]
Replaced with individual issues in dedicated provider repositories.
/close
