### ISSUE TITLE
Consider Azure AZs

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener-extensions#135]
We do not support AZs for Azure, but there seem to be some now: https://azure.microsoft.com/de-de/blog/introducing-azure-availability-zones-for-resiliency-and-high-availability/ -> https://azure.microsoft.com/en-us/global-infrastructure/availability-zones
What are the advantages of those AZs and should we support them (instead of the update and fault domains)?

**Comment by dkistner** [comment]
**Current Status**
- [x] 1. Move to Standard LoadBalancers
- [ ] 2. New `core.gardener.cloud/v1alpha1.Shoot` resource is implemented to allow zone assignments per workerpool on Azure
- [ ] 3. MCM supports Azure Availability Zones https://github.com/gardener/machine-controller-manager/issues/332
- [ ] 4. Azure Provider extension handle `infrastructure`, `controlplane` and `worker` CRs properly to support zones (depends partly on 2.) 
- [ ] 5. Gardener creates proper CRs in the Seed which the Azure provider extension can react on (depends on 2.)
