### ISSUE TITLE
[GCP] Deletion of a shoot cluster deletes all firewall rules in the same VPC and svc account

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener-extensions#158]
If two or more shoot clusters share the same VPC and are created by the same service account and then one of these clusters gets deleted all firewall rules for the VPC and service account also get deleted. 

Check:
https://github.com/gardener/gardener-extensions/blob/master/controllers/provider-gcp/pkg/internal/infrastructure/infrastructure.go#L35 
and
https://github.com/gardener/gardener-extensions/blob/master/controllers/provider-gcp/pkg/internal/infrastructure/infrastructure.go#L70

We should add an additional filter including the shoot's name when listing firewall rules for deletion, currently we only use the following prefixes: 

```go
const (
	KubernetesFirewallNamePrefix string = "k8s"
	shootPrefix                  string = "shoot--"
)
```

**Comment by rfranzke** [comment]
Thanks!

**Comment by vlerenc** [comment]
Thanks from me as well!

**Comment by plkokanov** [comment]
I'll most likely finish this by tomorrow. 
An Idea I will try out is to have the k8s-* firewalls be deleted by the cloud controller manager.

**Comment by rfranzke** [comment]
@plkokanov the CCM deletes these firewall rules normally. The reason why this explicit deletion has been implemented is because services of type load balancer don't have finalizers. That means that if such a service is deleted while CCM is down nothing will happen (firewall rules remain), and, eventually the infrastructure destruction is blocked.

**Comment by plkokanov** [comment]
@rfranzke alright, thanks for the input. So I'll just go with filtering by the shoot name/namespace.
for the k8s-* networks I can filter by the targetTags (which should be the shoot's namespace) and for the shoot-* networks I will use the whole shoot namespace as prefix.

**Comment by rfranzke** [comment]
This sounds good!
