### ISSUE TITLE
Update controller-runtime to 0.2.0-beta.4

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-extensions#163]
We have to update the controller-runtime to `v0.2.0-beta.4` in order to be able to vendor the `master` branch of Gardener again.

There is one larger problem with the `v0.2.0-beta.4` version, namely the removal of the certificate generation and automated webhook registration.

> Of particular note is that automatic certificate generation for webhooks has been removed, and webhooks will no longer self-register. Use controller-tools to generate a webhook configuration, and use something like cert-manager to generate your certificates (if you don't already have a solution). The next release of Kubebuilder will support this out-of-the-box.

We decided the most convenient way to fix this is to move the certificate generation as well as the webhook registration to the Helm chart of the providers themselves. For the local development case we might want to run a script as part of `make start-provider-<type>` that renders this part of the Helm chart and applies the configuration to the local Kubernetes cluster.

/cc @stoyanr

**Comment by timuthy** [comment]
Btw 0.2.0-beta.4 doesn't contain critical fixes (see [release notes](https://github.com/kubernetes-sigs/controller-runtime/releases)), so it's not that critical to bump to beta.4 at the moment.
