### ISSUE TITLE
Gardener shoot loadbalancer cleanup race condition (OpenStack)

### ISSUE THREAD

**Issue by kayrus** [gardener/gardener-extensions#180]
**What happened**:

When you remove the seed cluster, it stucks because loadbalancers cannot be removed.

**What you expected to happen**:

seed cluster removal should not stuck

**How to reproduce it (as minimally and precisely as possible)**:

create a seed cluster in openstack environment with lbaas support, then remove the seed cluster. The issue is not permanent, from my perspective it occurred every second time.

**Anything else we need to know?**:

some info about the environment: https://gist.github.com/kayrus/540feef00222e32a214c9f34f88319cb

Looks like `kube-apiserver` and `kube-addon-manager` deployments are removed without waiting the successful public ingress svc removal.

**Environment**:

- Gardener version: 0.24.0
- Kubernetes version (use `kubectl version`): soil cluster `1.12.9`
- Cloud provider or hardware configuration: OpenStack

**Comment by rfranzke** [comment]
Moved the issue to gardener/gardener-extensions

**Comment by kayrus** [comment]
@rfranzke can you show the reference to the code of the "manual" cleanup for AWS and GCP?

**Comment by rfranzke** [comment]
AWS:
* https://github.com/gardener/gardener-extensions/blob/master/controllers/provider-aws/pkg/controller/infrastructure/actuator_delete.go#L72-L80
* https://github.com/gardener/gardener-extensions/blob/master//controllers/provider-aws/pkg/controller/infrastructure/actuator_delete.go#L101-L123

GCP:
* https://github.com/gardener/gardener-extensions/blob/master//controllers/provider-gcp/pkg/controller/infrastructure/actuator_delete.go#L98-L114
* https://github.com/gardener/gardener-extensions/blob/master///controllers/provider-gcp/pkg/controller/infrastructure/actuator_delete.go#L31-L67

**Comment by afritzler** [comment]
@rfranzke you can assign me to this task.

**Comment by kayrus** [comment]
Temp workaround proposed: https://github.com/gardener/gardener-extensions/pull/191

**Comment by afritzler** [comment]
Together with #191 and https://github.com/gardener/gardener/pull/1273 this issue should be fixed now.
