### ISSUE TITLE
Extension OS Controllers does not reconcile the secrets: `osc-result-cloud-config*`.

### ISSUE THREAD

**Issue by KristianZH** [gardener/gardener-extensions#204]
Extension OS Controllers does not reconcile the secrets: `osc-result-cloud-config*`.

### Reproducing

Create cluster with `cores` machineImage. After that change it to `jeos` machineImage. The `Worker` will fall in error state because the machines will not be able to join the cluster.

**Comment by KristianZH** [comment]
Ping @pablochacin @vlvasilev

**Comment by vlvasilev** [comment]
[this function](https://github.com/gardener/gardener-extensions/blob/ec0737620f1e6f75ac33e405eadb63b306b6f90a/pkg/controller/predicate.go#L217) should be replace with `return typeMatches(updateEvent.ObjectNew)`.
Now we are using the old object for matching. In this case if you change the OS type from coreos to ubuntu we still are using the old type coreos. Thus OSC shall be reconsiled not by the ubuntu controller but by the coreos one.

**Comment by rfranzke** [comment]
Fixed after the merge of #178. Take a look at https://github.com/gardener/gardener-extensions/blob/master/pkg/predicate/predicate.go#L184-L195 - it now uses the new object for the update events when checking the type.
