### ISSUE TITLE
Control plane exposure controller

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-extensions#233]
We have introduced a `ControlPlane` CRD whose `spec` contains a `type` field for the respective shoot provider. It's purpose is to install any provider-specific components into the seed (or shoot) that are required to make the cluster functional. Examples of those components are the cloud-controller-manager, CSI controllers/plugins, or storage classes.

Some providers have additional needs: They might need to deploy components that are required to expose the control plane. The kube-apiserver of a shoot is exposed via a load balancer in the seed. The seed provider might be different from the shoot provider (for example, you can create an AWS shoot whose control plane is running on a GCP seed). Examples for those components are the [`aws-lb-readvertiser`](https://github.com/gardener/aws-lb-readvertiser). While most seed providers don't need to do anything here some might have this requirement.

The plan is to enhance the current `ControlPlane` resource (instead of creating an entirely new CRD named `ControlPlaneExposure`). Let's introduce a new `.spec.purpose` field whose possible values are `{exposure,normal}` (naming suggestions/improvements are welcome):

```yaml
apiVersion: extensions.gardener.cloud/v1alpha1
kind: ControlPlane
metadata:
  ...
spec:
  type: aws
  purpose: exposure
  ...
```

When seeing such a resource the AWS control plane exposure controller shall deploy the `aws-lb-readvertiser`.

The resource doesn't need to have any infrastructure information (because the infrastructure is created for the shoot cloud provider).

**Comment by rfranzke** [comment]
@svetlinas volunteered to take this.

**Comment by timuthy** [comment]
@rfranzke can you elaborate on the use-case `purpose: normal`?

**Comment by rfranzke** [comment]
The `purpose: normal` should trigger the `ControlPlane` controllers for the shoot provider, i.e., the currently implemented control plane controllers.
The `purpose: exposure` should trigger the new control plane controllers for the exposure settings.
