### ISSUE TITLE
MachineDeployment generations keeps increasing

### ISSUE THREAD

**Issue by prashanth26** [gardener/gardener-extensions#239]
## Issue
MachineDeployment generations are being increased on every shoot reconciliation even when the shoot(worker) spec hasn't changed. And when the shoot reconciliation is disabled the generations remain constant. 

## Observation
When I took a diff between the machine deployments between two reconciliations, I could only see the following fields changing - `metadata.Generation`, `metadata.ResourceVersion`, `Status.observedGeneration`. Not one field on the spec has changed. 

I had a quick look at the machineReconcile method, but couldn't find the root cause for the issue.

**Comment by rfranzke** [comment]
@prashanth26 should this be kept open? What can we improve? Or shall we close it?

**Comment by prashanth26** [comment]
I just checked a few seeds, and I see older `machineDeployments` with higher generations. However, the new ones have expected values. I think the issue has been fixed now due to the change in subresource. We can close it for now, and reopen if we ever see it again.
