### ISSUE TITLE
"Reconciler error" when removing extension resource

### ISSUE THREAD

**Issue by c0d1ngm0nk3y** [gardener/gardener-extensions#268]
What happened?

When removing an `extension` resource in the shoot namespace of a seed, the finalizer is called correctly. But in the log of the installation-controller, we find an error like

```
xxx-controller	Extension resource deletion successful, removing finalizer.	{"extension": "xxx", "namespace": "shoot--project-name--shoot-name"}
controller-runtime.controller	Reconciler error	{"controller": "xxx-controller", "request": "shoot--project-name--shoot-name/xxx", "error": "Extension.extensions.gardener.cloud \"xxx\" not found"}
```

This error is confusing/wrong since the removing worked fine.

To reproduce:

1. Create a `extension` resource in a shoot
1. After the extension is reconciled, remove the resource again
1. View log of extension-controller in in seed cluster

Note: Removing the extension from the shoot spec will not delete the extension resource https://github.com/gardener/gardener/issues/1338 delete it manually in the seed.

**Comment by rfranzke** [comment]
I think this has been fixed meanwhile, please reopen if you think it's not.
