### ISSUE TITLE
Circumvent k8s 1.15.3 bug for Azure cloud provider

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener-extensions#280]
K8s `1.15.3` has been released recently but this version is shipped with a bug in the Azure cloud provider (Cloud-Controller-Manager) which lets it crash loop constantly.

See: https://github.com/kubernetes/kubernetes/pull/81463

Nevertheless, we could circumvent this issue by using `cloudProviderBackoffMode: default` instead of `v2`.

https://github.com/kubernetes/kubernetes/blob/c7858aa97643c532ffb26a8ae9fa86611dd329a5/staging/src/k8s.io/legacy-cloud-providers/azure/azure.go#L137

@dkistner @rfranzke do you have any opinion / experience using the `default` mode or do you see any risk switching to it at least at the moment for `1.15.3` clusters only?

/cc @MSSedusch @ThormaehlenFred

**Comment by dkistner** [comment]
I think we should remain with `v2`. 
If I remember correct `default` means that the cloud provider + the azure go sdk will both backoff requests to the ARM. For `v2` it is relying only on the sdk backoff. That means we would reduce the amount of request to the ARM.

**Comment by vlerenc** [comment]
Yes, if no damage was done yet (it wasn't rolled out to any other than the dev/staging landscape), let's remain with v2. Good, that we saw that so early. That's why we have the dev/staging landscapes. :-)

**Comment by timuthy** [comment]
Okay, thanks for the information.

Let's close this now and wait for the fix to be delivered in `1.15.4`.
