### ISSUE TITLE
./hack/generate.sh does not work when project cloned outside of $GOPATH

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extensions#292]

**Comment by ialidzhikov** [comment]
The upstream issue kubernetes/kubernetes#86753 is accepted. It is currently limitation of `k8s.io/code-generator`.

**Comment by rfranzke** [comment]
Closing for now as repository has been split up and it seems that this issue is not too important and usually you are working inside your `$GOPATH`. Please reopen on the dedicated repositories if you think it should be fixed.
/close
