### ISSUE TITLE
Cannot vendor gardener/gardener@61b1a94eccba

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extensions#314]
I would like to vendor gardener/gardener@61b1a94eccba (which is needed fo golang-1.13).
Our approach during `hack/check-generate.sh` is to first clean all generated conversions, defaulters (`hack/clean.sh`), then run `hack/generate.sh` and then check the diff.
With gardener/gardener@61b1a94eccba the generation fails.

```
$ go get  github.com/gardener/gardener@61b1a94eccba
$ make revendor

$ ./hack/install-requirements.sh
$ ./hack/clean.sh
$ ./hack/generate.sh
controllers/provider-azure/pkg/apis/config/register.go:48:3: cannot use &ControllerConfiguration literal (type *ControllerConfiguration) as type runtime.Object in argument to scheme.AddKnownTypes:
	*ControllerConfiguration does not implement runtime.Object (missing DeepCopyObject method)
# github.com/gardener/gardener-extensions/controllers/provider-gcp/pkg/apis/gcp
controllers/provider-gcp/pkg/apis/gcp/register.go:48:3: cannot use &CloudProfileConfig literal (type *CloudProfileConfig) as type runtime.Object in argument to scheme.AddKnownTypes:
	*CloudProfileConfig does not implement runtime.Object (missing DeepCopyObject method)
controllers/provider-gcp/pkg/apis/gcp/register.go:49:3: cannot use &InfrastructureConfig literal (type *InfrastructureConfig) as type runtime.Object in argument to scheme.AddKnownTypes:
	*InfrastructureConfig does not implement runtime.Object (missing DeepCopyObject method)
[...]
```

**Comment by timuthy** [comment]
I've been also struggling with this and currently it seems like the `netpol-gen` causes that issue. I'll dig deeper.

**Comment by ialidzhikov** [comment]
In `gardener/gardener/pkg/apis/core/v1alpha1/conversions.go` we now import `openstackv1alpha1.CloudProfileConfig` and `azurev1alpha1.CloudProfileConfig` and use them as `runtime.Object`. When `./hack/cleans.sh` is ran, they cannot be used as `runtime.Object`.
I believe that is the issue.
