### ISSUE TITLE
Terraform deprecated arguments

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extensions#320]
Currently we use the following deprecated arguments:
- provider-azure:
  - azurerm_subnet.workers: "network_security_group_id" 
    ```
    Warning: azurerm_subnet.workers: "network_security_group_id": [DEPRECATED] Use the `azurerm_subnet_network_security_group_association` resource instead.
    ```
  - azurerm_subnet.workers: "route_table_id" 
    ```
    Warning: azurerm_subnet.workers: "route_table_id": [DEPRECATED] Use the `azurerm_subnet_route_table_association` resource instead.
    ```

- provider-alicloud
  - alicloud_nat_gateway.nat_gateway: "spec"
    ```
    Warning: alicloud_nat_gateway.nat_gateway: "spec": [DEPRECATED] Field 'spec' has been deprecated from provider version 1.7.1, and new field 'specification' can replace it.
    ```

**Comment by rfranzke** [comment]
@dkistner @AndreasBurger @jia-jerry @minchaow @EmoinLanyu can you please take a look?

**Comment by jia-jerry** [comment]
> @dkistner @AndreasBurger @jia-jerry @minchaow @EmoinLanyu can you please take a look?

Will check.

**Comment by dkistner** [comment]
Yep I will provide a pr to fix for azure soon.

**Comment by ialidzhikov** [comment]
We reverted the azure changes - ref #348. However we can only re-apply them when `terraform-providers/terraform-provider-azurerm` release v2.0.0 and we adopt this version.
