### ISSUE TITLE
Unable to create volumes on alicloud with specific CIDR 

### ISSUE THREAD

**Issue by schrodit** [gardener/gardener-extensions#367]
When creating a shoot with specific networking CIDR's kubernetes is unable to create the pvc with the error message:
```
Normal   ExternalProvisioning  13s (x2 over 19s)  persistentvolume-controller                                                                                  waiting for a volume to be created, either by external provisioner "diskplugin.csi.alibabacloud.com" or manually created by system administrator
Warning  ProvisioningFailed    9s                 diskplugin.csi.alibabacloud.com_csi-plugin-controller-78d89b9fd5-5tpgg_ca47ea55-ec22-11e9-83d0-4a4f7dd934ba  failed to provision volume with StorageClass "default": rpc error: code = DeadlineExceeded desc = context deadline exceeded
Normal   Provisioning          8s (x2 over 19s)   diskplugin.csi.alibabacloud.com_csi-plugin-controller-78d89b9fd5-5tpgg_ca47ea55-ec22-11e9-83d0-4a4f7dd934ba  External provisioner is provisioning volume for claim "default/redis-data-tetst"
```

**How to reproduce:**
1. Create a alicloud shoot with the following network configuration (e.g. https://github.com/gardener/gardener/blob/2253ecb2b16bacbc72dc944c82b8bca911a23f2c/example/90-shoot.yaml#L212)
```
networking:
    type: calico
    pods: 100.96.0.0/11
    nodes: 10.250.0.0/16
    services: 100.64.0.0/13
```

2. Create a PVC
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: diskplugin.csi.alibabacloud.com
  name: redis-data-tetst
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: default
  volumeMode: Filesystem

```

**Comment by rfranzke** [comment]
I think the CIDRs you used are not supported on Alicloud. Can you try with Alicloud's standards/defaults:

pods: 100.64.0.0/11
services: 100.104.0.0/13

**Comment by schrodit** [comment]
These cidr's (pods: 100.64.0.0/11 services: 100.104.0.0/13 ) are are working correctly.

**Comment by jia-jerry** [comment]
@schrodit , agree with @rfranzke , would you please use cidrs like below:
```
      networks:
        nodes: 10.250.0.0/16
        pods: 100.64.0.0/11
        services: 100.104.0.0/13
        vpc:
          cidr: 10.250.0.0/16
        workers:
          - 10.250.0.0/19
```
Alicloud reserves 100.100.** .

**Comment by schrodit** [comment]
Ok then we will will overwrite these cidrs in the tests.

Maybe we should add a comment somewhere that these cidr's are reserved.
Given that most people will copy the example from the gardener repo?

**Comment by rfranzke** [comment]
Yes, I'll add documentation for all providers today and will mention it. Thanks! Closing the issue now.
