### ISSUE TITLE
Maintain a compatibility matrix between g/g and g/g-e

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extensions#387]
Currently we don't maintain any compatibility matrix between gardener/gardener and gardener-extensions. Very often there are breaking changes that does not allow running given version of gardener/gardener with a given version of gardener/gardener-extensions.

**Comment by schrodit** [comment]
We would also need this for the gardener tests. I guess we have to have a wrapper repo like `garden-setup`?

**Comment by ialidzhikov** [comment]
> I guess we have to have a wrapper repo like `garden-setup`?

Could you please elaborate more? 
My initial idea was to have a markdown where the compatibility rules are written. This will help us and the g/g adopters.

**Comment by schrodit** [comment]
To give a bit more context. We somehow need to programatically know which gardener-extension versions we can install with a specific gardener version. Currently we know the relation because it is hardcoded in garden-setup but I think there should be a easier and more readable way of defining this matrix.

**Comment by rfranzke** [comment]
I hope that the frequency of "breaking changes" will drastically drop now that we have completed most major adaptions wrt extensibility. Though, we can still have this compatibility matrix in gardener/gardener-extensions, but gardener/gardener itself shouldn't know about any version constraints of the extensions library. Also, as soon as we split up the repository into single ones we would need this compatibility information per repository anyways. Should we wait until then or introduce a formal description already today?

**Comment by rfranzke** [comment]
Not needed anymore as the code of gardener/gardener-extensions is now maintained in gardener/gardener as of gardener/gardener#2141.
