### ISSUE TITLE
Infrastructure credentials validation

### ISSUE THREAD

**Issue by dkistner** [gardener/gardener-extensions#393]
**What would you like to be added**:
With the infrastructure provider extensions Gardener has moved out infrastructure dependencies, which gives us more flexibility to introduce also infrastructure specific checks.

We could extend the provider extensions to validate the user credentials to make sure the passed credentials are valid/not outdated and in the long term also that they have sufficient privileges. These checks should be triggered before Gardener start to create/reconcile/delete a Shoot cluster.

**Why is this needed**:
Give endusers early feedback if their Shoot clusters can be created/updated/deleted with the passed credentials and also avoid or reduce the occurrence of common error classes like `invalid credentials` or `insufficient privileges`.

**Comment by rfranzke** [comment]
We decided not to implement this as there won't be much benefit. We would have to have way more checks, e.g. whether sufficient quotas exist and privileges are provided. However, all these checks don't help when the end-user changes the credentials, revokes them on cloud provider side or runs out of its quota. Hence, we decided not to invest by now.
