### ISSUE TITLE
Health check controllers

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-extensions#406]
With https://github.com/gardener/gardener/pull/1523 Gardener has enabled extension controllers to contribute health check conditions to the `status` of the `Shoot` resource by adding them to the `status` of their extension resource. See also https://github.com/gardener/gardener/blob/master/docs/extensions/shoot-health-status-conditions.md.

We should now adapt all extensions to regularly write health status conditions such that Gardener can pick them up and such that the shoot status gets more accurate.

Also, we should ease implementing this health check controller for providers and improve our extensions library. For providers it should be possible to only implement the minimal specifics, e.g., they can provide the names of deployments, daemonsets, ... that should be checked, and a generic health controller will take over and write the conditions. We can follow the approaches of the `genericactuator` of `genericensurer` that we implemented for other controllers.

Specifically, the following needs to be done:

* [ ] Health check controller implementation in extensions library
* [ ] Generic health check actuator in extensions library
* Implementations for the extensions:
  * [ ] `extension-certificate-service`: *deprecated, will be removed soon*
  * [ ] `extension-shoot-cert-service`: Check `Deployment` of `cert-controller-manager`
  * [ ] `extension-shoot-dns-service`: Check `Deployment` of `dns-controller-manager`
  * [ ] `networking-calico`: Check `DaemonSet` of `calico-node`; `Deployment` of `calico-typha`, `calico-kube-controllers`, etc.
  * [x] `os-coreos-alicloud`: nothing
  * [x] `os-coreos`: nothing
  * [x] `os-suse-jeos`: nothing
  * [x] `os-ubuntu-alicloud`: nothing
  * [x] `os-ubuntu`: nothing
  * [ ] `provider-alicloud`: Check `Deployment` of `cloud-controller-manager`, `csi-controller`, and `machine-controller-manager` and in the Shoot the `csi-driver` `Deployment`
  * [ ] `provider-aws`: Check `Deployment` of `cloud-controller-manager` and `machine-controller-manager`
  * [ ] `provider-azure`: Check `Deployment` of `cloud-controller-manager` and `machine-controller-manager`
  * [ ] `provider-gcp`: Check `Deployment` of `cloud-controller-manager` and `machine-controller-manager`
  * [ ] `provider-openstack`: Check `Deployment` of `cloud-controller-manager` and `machine-controller-manager`
  * [ ] `provider-packet`: Check `Deployment` of `cloud-controller-manager` and `machine-controller-manager`

Part of https://github.com/gardener/gardener/issues/308.

@danielfoehrKn offered to work on this topic, but I'm not sure what's the current status because he got busy with other things. Can you share the current progress?

**Comment by danielfoehrKn** [comment]
Thanks for writing this issue!
No real progress so far, but I think I can start working on it next week - currently waiting input for my other tasks.

**Comment by danielfoehrKn** [comment]
Requiring [Gardener PR](https://github.com/gardener/gardener/pull/1647)
