### ISSUE TITLE
Terraformer cleans jobs and pods out of its namespace

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extensions#424]
Currently terraformer cleans up `tf-pod` and `tf-job` pods before and after each execution. It selects these pods with the label selector `job-name=<name>.infra.tf-job`. 

https://github.com/gardener/gardener/blob/61be4c73ac1acf85b2f8ae68bd7c1a6943b7fe7e/pkg/operation/terraformer/terraformer.go#L443-L450

The issue is that if there is another Shoot with the same name on the same seed, the terraformer will delete the pods also for this Shoot. As we already know, the deletion of `tf-job` leads to new `tf-job` pod by the job controller and we end up with 2 `tf-job` pods which result in `Infrastructure` that fails to create because of conflicts.

Steps to reproduce:
1. Create a Shoot with name `my-shoot` in project `proj1`
2. Simultaneously create a Shoot with name `my-shoot` in project `proj2` and ensure it is placed on the same Seed as the first Shoot.
3. Ensure that during the parallel creation one of Shoots will end up with `Infrastructure` that fails to create because of conflicts.

**Comment by vlerenc** [comment]
Oho, regardless of the namespaces. Nice catch, thanks!

**Comment by rfranzke** [comment]
WTF... yes, thanks for catching this. Got introduced with gardener/gardener#717, see https://github.com/gardener/gardener/commit/a3bd39c32c43d24326d0c43422ccfb84c1c6d9d9#diff-14406e13871bd6f15d602b0aeeaddfe2R406.
