### ISSUE TITLE
Support Service.spec.loadBalancerIP with Kubernetes services of type LoadBalancer

### ISSUE THREAD

**Issue by stephanzlatarev** [gardener/gardener-extensions#430]
Feature request: Applications with exposed static IP addresses, for the purpose to be white-listed by consumers, need to be able to re-use the IP addresses in case shoots are created, for example in a disaster recovery scenarios. This feature should be available with all cloud providers, i.e. be part of the homogeneity of clusters.

In the case of shoots in Azure:
```
Given I have an Azure resource group with name: my-resource-group
And I have a Virtual Network with name: my-virtual-network
And I have a Public IP address with:
  Name: my-public-address
  IPAddress: 51.105.156.156

When I create a Gardener shoot as:
  kind: Shoot
  apiVersion: garden.sapcloud.io/v1beta1
  metadata:
    name: my-shoot
  spec:
    cloud:
      profile: az
      azure:
        networks:
          vnet:
            resourceGroup: my-resource-group
            name: my-virtual-network
And I create a service in my-shoot shoot as:
  kind: Service
  apiVersion: v1
  metadata:
    name: my-load-balancer
  spec:
    type: LoadBalancer
    loadBalancerIP: 51.105.156.156

Then my-load-balancer service should be created successfully with:
  .status.loadBalancer.ingress[0].ip: 51.105.156.156
```

Currently this scenarios fails with error message:
```
user supplied IP Address 51.105.156.156 was not found in resource group shoot--garden--my-shoot
```

**Comment by dkistner** [comment]
The k8s azure cloud provider has the `service.beta.kubernetes.io/azure-load-balancer-resource-group: <my-ips-resource-group>` annotation, which should allow to use static public ips which are located in other resource groups. 
This should help to use pre-created static public ip in the cluster. These public ip should't be deleted when the corresponding service resource is deleted.

**Comment by stephanzlatarev** [comment]
It works. Thanks a lot!

https://docs.microsoft.com/en-us/azure/aks/static-ip#use-a-static-ip-address-outside-of-the-node-resource-group
