### ISSUE TITLE
make generate not compatible with Helm 3

### ISSUE THREAD

**Issue by afritzler** [gardener/gardener-extensions#446]
It looks like the `make generate` command is not properly working with Helm 3 (https://helm.sh/docs/topics/v2_v3_migration/).

**Comment by ialidzhikov** [comment]
https://github.com/gardener/gardener-extensions/blob/1.0.0/hack/install-requirements.sh#L28

You could use `./hack/install-requirements.sh`.

**Comment by afritzler** [comment]
Thanks @ialidzhikov will do that!
