### ISSUE TITLE
Add support for networking-cilium as CNI Plugin

### ISSUE THREAD

**Issue by soumynathan** [gardener/gardener-extensions#495]
Based on the move towards extensible framework, we should add additional networking plugins as extension.
This issue targets adding networking-cilium extension to the list of supported network extensions.
Cilium is open source software for transparently securing the network connectivity between application services deployed using Linux container management platforms like Docker and Kubernetes that depends on the new Linux kernel technology called BPF.

**Comment by vpnachev** [comment]
We've already have issue about cilium #129.
Do you mind if I close this one in favor of the above mention issue?

**Comment by soumynathan** [comment]
Sorry I was not aware about it. Please go ahead and close it and probably if you have not assigned a person on #129, you can assign me.
