### ISSUE TITLE
[Idea] Adding Kubevirt Support for Local Development

### ISSUE THREAD

**Issue by afritzler** [gardener/gardener-extensions#522]
Hi all,

since the work on the Kubevirt support for Gardener is progressed quite nicely[0], I wanted to suggest the following:

How about adding the Kubvirt Support into Gardener and MCM (currently everything is a hard fork)? The idea here would be to use your local minikube as the Gardener Cluster, the seed + the "IaaS" thanks to Kubevirt. 

In your minikube you would additionally install:
* Kubevirt controller
* Metal-lb (need to check how good that works)
* Using nip.io for DNS 

The advantage of this setup in contrast to the Vagrant based one we currently have is, that from an architectural point of view it fits into the Gardener model like any other IaaS we support. Of course you could still use Kubevirt in a non-local dev setup as well.

I just wanted to start a discussion here and see what you guys think and if there would be need for such thing? Otherwise we can postpone that and do the integration via our extension model.

Regards,
Andreas

/cc @gonzolino 

[0] https://github.com/kubeforge

**Comment by rfranzke** [comment]
Let's close this issue in favour of https://github.com/gardener/gardener-extension-provider-mock/issues/1
