### ISSUE TITLE
Azure cloud-controller-manager RBAC for serviceaccount "system:serviceaccount:kube-system:azure-cloud-provider"

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extensions#531]
Currently the azure cloud-controller-manager has multiple error logs :
```
'events "kube-apiserver.15e7ebd2126cb9f8" is forbidden: User "system:serviceaccount:kube-system:azure-cloud-provider" cannot patch resource "events" in API group "" in the namespace "shoot--foo--bar"' (will not retry!)
```

According to kubernetes/kubernetes#68212 the ClusterRole `system:azure-cloud-provider` and ClusterRoleBinding `system:azure-cloud-provider` needs to be created.

**Comment by rfranzke** [comment]
> User "system:serviceaccount:kube-system:azure-cloud-provider"

How is the Azure CCM using a service account of the `kube-system` NS?
