### ISSUE TITLE
SLBs are left after some round of e2e test in Alicloud

### ISSUE THREAD

**Issue by jia-jerry** [gardener/gardener-extensions#539]
We found issues that SLBs (Service load balancer) are left after belonging shoot cluster is deleted. This often ocurrs when e2e are run in the cluster.

**Comment by rfranzke** [comment]
You might want to implement dedicated deletion of LBs like in AWS or GCP

**Comment by jia-jerry** [comment]
It looks like a workaround in AWS. LBs should be taken care of by CCM.  Anyway, it works. But for Alicloud, LB has no relationship with VPC. Need further investigation.

**Comment by rfranzke** [comment]
It is a workaround. The correct solution is let the Alicloud CCM use finalizers for load balancer services.
