### ISSUE TITLE
Google infrastructure extension: cannot delete cluster that couldn't be created because of missing service account json

### ISSUE THREAD

**Issue by mandelsoft** [gardener/gardener-extensions#577]
If the account secret does not contain a service account json, the cluster can for sure not be created.
But when trying to delete such a cluster this fails because of the same reason:

```
Waiting until shoot infrastructure has been destroyed
Last Error
task "Waiting until shoot infrastructure has been destroyed" failed: Failed to delete infrastructure: Error deleting infrastructure: secret shoot--berlin--rg-kyma/cloudprovider doesn't have a service account json
```

**Comment by ialidzhikov** [comment]
It is the same also for the other providers. This is not something specific to gcp.

**Comment by rfranzke** [comment]
Replaced with individual issues in dedicated provider repositories.
/close
