### ISSUE TITLE
SIGTERM is not sent to terraformer process

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extensions#597]
**What happened**:
terraformer package starts the terraformer Pod with
```yaml
  containers:
  - command:
    - sh
    - -c
    - sh /terraform.sh apply 2>&1; [[ -f /success ]] && exit 0 || exit 1
```

When the terraformer Pod needs to be terminated, kubelet sends SIGTERM signal to pid 1. But the process that actually gets the SIGTERM in this case is `sh`, but not `/terraform.sh`.
The shell shipped by default with Alpine Linux does not pass signals to children and `/terraform.sh` does not receive a SIGTERM to start a graceful termination.

See a really nice explanation at https://pracucci.com/graceful-shutdown-of-kubernetes-pods.html.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy a terraformer pod with a relatively small `.spec.activeDeadlineSeconds` and `.spec.terminationGracePeriodSeconds` to be able to properly reproduce the issue. For example use `60` seconds instead of `630` seconds which is the value that the extension controllers pass to the terraformer obj.

2. Ensure that the Pod has a spec containing

```yaml
spec:
  activeDeadlineSeconds: 60
  terminationGracePeriodSeconds: 60
  containers:
  - command:
    - sh
    - -c
    - sh /terraform.sh apply 2>&1; [[ -f /success ]] && exit 0 || exit 1
```

Basically the terraformer package also sets `activeDeadlineSeconds` to `terminationGracePeriodSeconds` which is the amount of time to wait before SIGKILL is sent.

3. Apply the Pod

4. Delete the Pod after 10-20s of its initial start to simulate kubelet eviction or any other reason that can lead to Pod termination.

5. Get the logs of the terraformer Pod and ensure that it is running after the delete request is sent to the Pod. 

6. Ensure that after `terminationGracePeriodSeconds` (in our steps it is 60 seconds) the Pod will be killed and the terraformer process won't update anything in the state ConfigMap. Meanwhile the terraformer process already created several resources.

7. Ensure that if you deploy a second terraformer Pod (basically it is what the infrastructure controller does), it will fail with conflicts as the resources were already created with the previous run but the state for them was not preserved. 

**Environment**:

- gardener-extension-provider-aws: v1.3.0

**Comment by vlerenc** [comment]
Very nice catch!

**Comment by ialidzhikov** [comment]
Sorry, I delayed the work on this. Assigning to myself right now.

**Comment by rfranzke** [comment]
Thanks Ismail!

**Comment by ialidzhikov** [comment]
Actually, the recommendation in the guide to use `bash` instead of `sh` seems to do not work for our case. If we have:
- `foo.sh`
```sh
#!/bin/bash -eu

function end_execution() {
  # Delete trap handler to avoid recursion
  trap - HUP QUIT PIPE INT TERM EXIT

  echo "SIGTERM received"
}

trap end_execution INT TERM EXIT

echo "Sleeping"
sleep 3600 & wait $!
```

- `Dockerfile`
```docker
FROM alpine:3.10.3 AS base

RUN apk add --update bash

WORKDIR /

ADD ./foo.sh /foo.sh

CMD exec /foo.sh
```

- `pod.yaml`
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - command:
    - bash
    - -c
    - bash /foo.sh; echo 'foo'
    image: # ...
    imagePullPolicy: IfNotPresent
    name: container
```

- `ps -ef` output:
```
$ k exec -ti pod -- sh
/ # ps -ef
PID   USER     TIME  COMMAND
    1 root      0:00 bash -c bash /foo.sh; echo 'foo'
    8 root      0:00 bash /foo.sh
    9 root      0:00 sleep 3600
   10 root      0:00 sh
   17 root      0:00 ps -ef
```

Logs of `pod` after pod deletion:
```
$ k logs pod -f
Sleeping
```

---

I managed to do it with `exec`. The only diff is in the `pod.yaml`:
- `pod.yaml`
```yaml
spec:
  containers:
  - command:
    - sh
    - -c
    - exec /foo.sh; echo 'foo'
```

- `ps -ef` now outputs:
```
$ k exec -ti pod -- sh
/ # ps -ef
PID   USER     TIME  COMMAND
    1 root      0:00 {foo.sh} /bin/bash -eu /foo.sh
    8 root      0:00 sleep 3600
    9 root      0:00 sh
   16 root      0:00 ps -ef
```

Logs of `pod` after pod deletion:
```
$ k logs sh-test -f
Sleeping
SIGTERM received
```

---


However using `exec` I see one more issue. Even sending SIGTERM to `terraform.sh`, it does not interrupt the running terraform operation and does not update the state cm.
From https://www.gnu.org/software/bash/manual/html_node/Signals.html#Signals

> If Bash is waiting for a command to complete and receives a signal for which a trap has been set, the trap will not be executed until the command completes.

Let's reproduce in a smaller context:
- `foo.sh`

```bash
#!/bin/bash -eu

function end_execution() {
  # Delete trap handler to avoid recursion
  trap - HUP QUIT PIPE INT TERM EXIT

  echo "$(date) SIGTERM received"
}

trap end_execution INT TERM EXIT

echo "$(date) Sleeping"
sleep 3600
```

```
$ ./foo.sh
Sun Feb 23 22:40:12 EET 2020 Sleeping
```

We won't be able to SIGTERM and bash will wait for sleep to exit before calling the trap.
```
$ kill -15 $pid
```

So one of the workarounds that I found is to use `wait`. 

- `foo.sh`

```bash
#!/bin/bash -eu

function end_execution() {
  # Delete trap handler to avoid recursion
  trap - HUP QUIT PIPE INT TERM EXIT

  echo "$(date) SIGTERM received"
}

trap end_execution INT TERM EXIT

echo "$(date) Sleeping"
sleep 3600 & wait $!
```

---

Initially I had some question about terraform itself - whether it updates the state right before and after each operation or it is doing it once at the end of exection or something else.
From what I see, it is rather updating after each operation. Even for some resources in process of creation, I was able to see corresponding entry in the state file (with empty body). Which is good. However I tried to check the corresponding source from terraform side but no success with it.

I still have question marks here as during my tests for a running `terraform apply` I sent a SIGTERM (which does not kill the terraform apply but updates only the current state configmap if there is a diff) and the next terraformer pod failed with quite a lot of AlreadyExists errors.

@rfranzke , I guess we have also gracefully shutdown the running terraform operation on SIGTERM before invoking `end_execution`?

**Comment by rfranzke** [comment]
Thanks for digging into it @ialidzhikov. Can't we build a script that starts the `terraform.sh`, and if it receives a `SIGTERM` it forwards the signal to the `terraform.sh`. Then it waits until it has completed before updating the state configmap - would this work?

**Comment by ialidzhikov** [comment]
> Can't we build a script that starts the terraform.sh, and if it receives a SIGTERM it forwards the signal to the terraform.sh?

Currently we can adapt the terraformer pod to forward SIGTERM to `terraform.sh`. My question was rather what is the expected behaviour for `terraform.sh` on SIGTERM?

> Then it waits until it has completed before updating the state configmap - would this work?

We wait for the terraform command itself to terminate or? What happens if it cannot terminate for `.spec.activeDeadlineSeconds` as described in this issue, we again lose the state?

**Comment by ialidzhikov** [comment]
After re-checking the logs I have cleaner steps to reproduce:

1. terraformer Pod is created with `.spec.activeDeadlineSeconds=630` and `.spec.terminationGracePeriodSeconds=630`.
2. If the terraform operation cannot be completed for 630 seconds, the terraformer Pod is marked as failed (`.status.phase=Failed` and `.status.reason=DeadlineExceeded`).
3. After that ,terraformer pkg tries to clean up the Pod. And the surprise here at least for me is that the deletion of such DeadlineExceeded Pod completes right away without respecting `.spec.terminationGracePeriodSeconds=630`.
4. The state ConfigMap is still empty at this moment and multiple resources are created in the cloud provider.
5. After the requeue time (I guess ~30seconds), new terraformer Pod is created and it fails with AlreadyExists errors.

I actually reproduced this with
```diff
	return tf.
-		SetActiveDeadlineSeconds(630).
+		SetActiveDeadlineSeconds(45).
		SetDeadlineCleaning(5 * time.Minute).
		SetDeadlinePod(15 * time.Minute), nil
```

**Comment by rfranzke** [comment]
> Currently we can adapt the terraformer pod to forward SIGTERM to terraform.sh. My question was rather what is the expected behaviour for terraform.sh on SIGTERM?

I'm not too deep into the details, but I would assume it should forward SIGTERM to the `terraform apply/destroy` process that it started, wait until it finished, and then update the state configmap. Only then it should exit. WDYT?

> We wait for the terraform command itself to terminate or? What happens if it cannot terminate for .spec.activeDeadlineSeconds as described in this issue, we again lose the state?

I don't think we can prevent this. If you run a process that creates external state and is expected to store it, and if you kill it then after a few seconds then it won't save the state, of course. This behaviour should rather be documented properly and is in the responsibility of the user to configure it appropriately.

**Comment by timuthy** [comment]
> 3. After that ,terraformer pkg tries to clean up the Pod. And the surprise here at least for me is that the deletion of such DeadlineExceeded Pod completes right away without respecting .spec.terminationGracePeriodSeconds=630.

Can `preStop` help here?

**Comment by ialidzhikov** [comment]
We outlined the following items to complete/double-check:
1. Currently we observe that when the Pod is DeadlineExceeded, SIGTERM is sent. After `.spec.terminationGracePeriodSeconds`, SIGKILL is automatically sent. 
But the Pod status is not properly reflecting this and it is saying that the Pod is currently in running state even after SIGKILL is sent.
```yaml
status:
    state:
      running:
        startedAt: "2020-02-26T10:21:49Z"
```

As mitigation, in the terraformer pkg we can wait for `.spec.terminationGracePeriodSeconds` + (some buffer on top) before sending delete request to the Pod (as the delete request for DeadlineExceeded Pod will kill it right away).

2. We need to adapt terraformer tool handling for SIGTERM and forward SIGTERM also to the terraform command itself. State should be updated only when the terraform operation is completed.

**Comment by ialidzhikov** [comment]
> 3. After that ,terraformer pkg tries to clean up the Pod. And the surprise here at least for me is that the deletion of such DeadlineExceeded Pod completes right away without respecting .spec.terminationGracePeriodSeconds=630.

Actually, the delete request for such DeadlineExceeded Pod completes right away and the Pod is removed from the store, but I see that the associated container on the Node runs/lives for `.spec.terminationGracePeriodSeconds` before it is SIGKILL-ed.
And at least for me this behaviour is not consistent as for a Running Pod you will have a Pod in Terminating for `.spec.terminationGracePeriodSeconds` and when the Pod is removed from the store, you can assume that the containers are terminated.

**Comment by dguendisch** [comment]
> Actually, the delete request for such DeadlineExceeded Pod completes right away and the Pod is removed from the store, but I see that the associated container on the Node runs/lives for .spec.terminationGracePeriodSeconds before it is SIGKILL-ed.

Interesting, just yesterday while debugging some other problem between tf and openstack I noticed that weird behaviour too: the tf pod got deleted from the cluster, but seems to live on for some more seconds. In that time somehow the network is already shut down and it couldn't connect e.g. to DNS anymore, tf only recorded/printed the last error (dns lookup timeout), led us to the wrong path intially...

**Comment by ialidzhikov** [comment]
I opened https://github.com/kubernetes/kubernetes/issues/88611 and https://github.com/kubernetes/kubernetes/issues/88613.
I think we can remove activeDeadlineSeconds config. We already have deadlinePod config which is the amount of time to wait for the terraformer Pod to finish, then we have also terminationGracePeriodSeconds - the amount of time for graceful deletion. In this way we will prevent having a DeadlineExceeded Pod which deletion leaks running container.

**Comment by zanetworker** [comment]
@dguendisch that could be because of the lack of `preStop` hook, the endpoint controller can be pretty quick removing the ep from the service endpoint list but `kube-proxy` might not have been equally fast, as a result, iptable rules might still point to a dead endpoint and connection will fail.

**Comment by dguendisch** [comment]
@zanetworker I don't think so, the issue was a tf pod failing to communicate with coredns. The pod deleted was the tf pod and when in "zombie" mode (deleted in k8s but its container still running on the node) it failed to talk to coredns more or less reproducibly. The tf pod does not have endpoints.
