### ISSUE TITLE
Docker build fails 

### ISSUE THREAD

**Issue by afritzler** [gardener/gardener-extensions#60]
As of today the docker build seems to be failing installing helm

``` docker build .
Sending build context to Docker daemon  65.21MB
Step 1/20 : FROM golang:1.11.5 AS builder-base
 ---> 901414995ecd
Step 2/20 : COPY ./hack/install-requirements.sh /install-requirements.sh
 ---> Using cache
 ---> de1a213412cc
Step 3/20 : RUN /install-requirements.sh
 ---> Running in 9287d04f4ee8
Installing requirements
Downloading https://kubernetes-helm.storage.googleapis.com/helm-v2.13.1-linux-amd64.tar.gz
Preparing to install helm and tiller into /usr/local/bin
helm installed into /usr/local/bin/helm
tiller installed into /usr/local/bin/tiller
Run 'helm init' to configure helm.
The command '/bin/sh -c /install-requirements.sh' returned a non-zero code: 1
```

Somebody an idea what happened there?

**Comment by rfranzke** [comment]
cc @adracus

**Comment by adracus** [comment]
I'll take a look - seems like something with the helm install script broke. I'll try to pin the helm version + script repo path version and fix it so it won't happen again.

**Comment by adracus** [comment]
I'm correcting myself - nothing wrong with helm, but with the `uname -s` construct that checks whether to emit the macos warning or not. Seems like this caused the script to break. I'll provide a fix for that that should be merged soon.
