### ISSUE TITLE
Cluster creation hangs due to subnet conflicts

### ISSUE THREAD

**Issue by wgabsi88** [gardener/gardener-extensions#620]
**What happened**:
The cluster creation in a dedicated VPC is hanging due to subnet conflicts where the subnets are actually newly created by Gardener and should belong to the cluster. 

we had two scenarios :
1- the subnets have the correct names which contains the cluster name 
2- the subnets does not have any name 

**What you expected to happen**:
the newly created subnets should be used by the cluster without attempting to recreate the same subnets.

**Comment by rfranzke** [comment]
Probably related to https://github.com/gardener/gardener-extensions/issues/597 ...
